// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwS1pPhqD7QzGu2BCYebpCLfdirExqM7E',
    appId: '1:604624274774:android:f8cd6b04aa9a5388fbc2f7',
    messagingSenderId: '604624274774',
    projectId: 'chat-app-a5119',
    storageBucket: 'chat-app-a5119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTW_mQccFwiIpyHbodsLA176kAq-bOC2w',
    appId: '1:604624274774:ios:02b15d2c6d643698fbc2f7',
    messagingSenderId: '604624274774',
    projectId: 'chat-app-a5119',
    storageBucket: 'chat-app-a5119.appspot.com',
    iosClientId: '604624274774-71bbbsn7rto6oskto8vrk9f59b6t8auo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
